name: Renovate

on:
  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Self-host Renovate
        uses: renovatebot/github-action@v40.1.0
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          renovate-config: ".renovaterc"
